# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-KmAMEPkkwS47VdxlXTWAkNdibsPP3Q
"""

def kasallik_tashxisi(belgi):
  if belgi== "istima":
   return "Parastamol iching"
  elif belgi== "Bosh og'rig'i":
   return "Bolnol"
  elif belgi== "Tish ogrigi":
   return "Sinipar"
  else:
   return "Shifokorga murajat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)